### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy 

### ISSUE THREAD

**Issue by Jai-Gogineni** [wswebcreation/multiple-cucumber-html-reporter#200]
I try to integrate with jenkins, but i am getting the above error when opened through jenkins reports, how can i fix this with report generation.

![image](https://user-images.githubusercontent.com/6741795/178247969-21822aa2-5559-49ab-ac78-869ad12dc439.png)

Thanks for the help in advance !

**Comment by wswebcreation** [comment]
Hmm, never seen this issue before, can you also post your config here?

**Comment by Jai-Gogineni** [comment]
HI, What config you would like to know ?

I use Cucumber with cypress along with "multiple-cucumber-html-reporter": "1.21.4",

**Comment by wswebcreation** [comment]
Sorry for my late reply, the config of this module, how do you start it, see https://github.com/wswebcreation/multiple-cucumber-html-reporter#usage

**Comment by BaCaRoZzo** [comment]
@Jai-Gogineni you can help us by telling what is the exact code that is failing in `index.html`. Otherwise it's a bit like shooting in the dark.

The report is part of our artifacts in `Jenkins` and we don't have much of a problem. Not sure if we have relaxed CSP for that, but after a quick check, it doesn't seem the case.

**Comment by wswebcreation** [comment]
Closing this one due to inactivity. Feel free to reopen it if you have more information.
