### ISSUE TITLE
Show parameters value of outline examples 

### ISSUE THREAD

**Issue by brbernardo90** [wswebcreation/multiple-cucumber-html-reporter#3]
Image of the .feature:

![report_issue4](https://user-images.githubusercontent.com/15858324/28036246-fe953b68-658d-11e7-84cd-81fdfb844f52.png)

Image of the report:

![report_issue5](https://user-images.githubusercontent.com/15858324/28036315-32bf5518-658e-11e7-9b0c-dc9092370045.png)

**Comment by wswebcreation** [comment]
Hi,

Can you please provide all the info as mentioned in your first issue so I can see what the problem is?

Based on what I see now, (issue 1,2,3) I think it has more to do with the language that is not adding all the data to the json, than that his is an issue in the reporting module

**The feature**
![image](https://user-images.githubusercontent.com/11979740/28038291-af08872c-65be-11e7-81f4-492f0741ee9e.png)


**The output**
![image](https://user-images.githubusercontent.com/11979740/28038266-9c73801c-65be-11e7-8b08-8e7550dcbc6d.png)

**Comment by wswebcreation** [comment]
Hi @brbernardo90 

Is this still valid?

**Comment by wswebcreation** [comment]
Closed due to inactivity
