### ISSUE TITLE
How about Total time of all features

### ISSUE THREAD

**Issue by muthukumarse** [wswebcreation/multiple-cucumber-html-reporter#38]
any plan for this features
- show total feature run time on Feature Overview Page
- customise HTML head title 
- customise header/footer template

**Comment by wswebcreation** [comment]
Hi @muthukumarse 

Here's my reaction

> show total feature run time on Feature Overview Page

See the note add (displayduration)[https://github.com/wswebcreation/multiple-cucumber-html-reporter#displayduration] because of possible parallel execution. We can use a option for it that is defaulted to `false`, care for a PR?

> customise HTML head title

See [`reportname`](https://github.com/wswebcreation/multiple-cucumber-html-reporter#reportname)

> customise header/footer template

What do you mean with this?

**Comment by muthukumarse** [comment]
@wswebcreation 

I pushed the changes I made and requested PR39 please go through.

Cheers.

**Comment by muthukumarse** [comment]
please update the change log if changes are good to go 👍

**Comment by muthukumarse** [comment]
For totalling for all features Duration, Total, Passed, Failed in features-overview.
I will check and keep you posted.

**Comment by muthukumarse** [comment]
@wswebcreation - ? :)

**Comment by muthukumarse** [comment]
@wswebcreation - sure, please do when you have time.

**Comment by wswebcreation** [comment]
@muthukumarse I've already checked it yesterday, you can see the feedback in the PR

**Comment by wswebcreation** [comment]
Going to close it. The referred PR https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/39 is already merged
