### ISSUE TITLE
Combining reports from initial run and rerun

### ISSUE THREAD

**Issue by jacekokrojek** [wswebcreation/multiple-cucumber-html-reporter#40]
Hi 

I wonder if there is a way to combine results from cucumber initial run and rerun in a way that most recent results are presented in the report. If a test passed during the rerun I would like reporter to be smart enough to override previous failure.

I would be grateful for answer

Jacek

**Comment by wswebcreation** [comment]
Hi @jacekokrojek 

The report itself should be as dumb as possible. It should not overwrite files / combine them in the first place because it isn't attached to the running session. It runs after all tests are done so it doesn't know what belongs to each other.

If you want to combine files you need to make a customer process before you generate your reports.

I'm going to close it for now but it's still open for discussion
