### ISSUE TITLE
Pragmatically add metadata within cucumber?

### ISSUE THREAD

**Issue by lenntt** [wswebcreation/multiple-cucumber-html-reporter#42]
Using cucumber 4 (seems no reason why that wouldnt work like 3?), so I have a post cucumber script to translate json to html.

I'm a bit stuck trying to get my environment variables (browser name, app version etc.) into the cucumber json file DURING cucumber execution.

I don't think cucumber offers an `attach`, or any way to just fiddle yourself with the testcase to get the metadata in the json? 
Do I have to create my own formatter - forked from the json formatter?

An example, documentation or formatter would really help me.

**Comment by wswebcreation** [comment]
Hi @lenntt 

I'm not working with plain CucumberJS, so I don't know how to do that. If you figured it out I'd really like to know and if you want you can add a PR to update the docs.

I'm going to close it for now because this isn't a question / issue related to this module. It's still open for discussion.
