### ISSUE TITLE
Multiple cucumber_output (json) into Single Report with different Metadata

### ISSUE THREAD

**Issue by muthukumarse** [wswebcreation/multiple-cucumber-html-reporter#82]
Hi @wswebcreation 

Now I have 2 set of test executions
1. puppeteer chrome
2. puppeteer firefox
both produce 2 different JSON output. 

Able to produce a single report by pointing outputDir. 

But I want to feed different metadata for each output.

What I see we have only metadata which applied for all output files

I made a small change in collect-json.js to adopt different metadata for each output file 

metadata sample
-------------------
```
metadata: {
    "cucumber_report_chrome": {
      browser: {
        name: 'chrome',
        version: '68.0.3419.0'
      },
      device: 'Local Test Machine',
      platform: {
        name: 'linux',
        version: 'x86_64'
      },
    },
    "cucumber_report_firefox": {
      browser: {
        name: 'firefox',
        version: '65.0'
      },
      device: 'Local Test Machine',
      platform: {
        name: 'linux',
        version: 'x86_64'
      },
    }
}

```
cucumber_report_chrome
cucumber_report_firefox 
these are output filenames (without json) which produced by cucumberjs execution.

How do you see this? should raise the PR for the changes.

I made it as additional if block to accept if there is multiple metadata otherwise it will go as global one which applied all the files.

( I don't find an easy way to add metadata inside cucumberjs report )

**Comment by wswebcreation** [comment]
Hi @muthukumarse,

I think there is some misunderstanding on the metadata part. Please check this part in the docs

https://github.com/wswebcreation/multiple-cucumber-html-reporter#metadata

and especially this remark

> **If you provide the metadata when instantiating multi-cucumber-html-reporter the metadata will be added to each feature. If you already have metadata in your JSON then the metadata in the JSON will take precedence** 

This means that you need to provide it yourself per instance, so per generated JSON file in your framework, or you provide a capability for generating the report, but then it will be used for all

I'm going to close it for now, but it's still open for discussion

**Comment by muthukumarse** [comment]
Hi @wswebcreation 

I understood and was using the same way you pointed out.

now I have a situation that, I am producing more than one output (JSON output) and when I am producing HTML report I want each file should have own metadata instead of same.

in my case 1 output which ran in puppeteer chrome, another one puppeteer-firefox. once I generate the HTML output, I want different metadata info for each of those.

**Comment by wswebcreation** [comment]
That can be reached by having it in per json file, the module will print it to a nice report, just check the example files [here](https://github.com/wswebcreation/multiple-cucumber-html-reporter/tree/master/test/unit/data/json). There you will see that all these files have their own metadata and it will be printed to this report which you can find [here](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html)

**Comment by muthukumarse** [comment]
@wswebcreation 
this is what I am trying to get it done, is there way to push the metadata inside report json through cucumber-js command

**Comment by wswebcreation** [comment]
I don't know the tool you are using, but you should be able to do that in a post-process when the json file has been stored, open it and add the data

**Comment by muthukumarse** [comment]
@wswebcreation Yes can be achieved by post-process step. But I see that collect-json.js does the same in "multiple-cucumber-html", I thought we should extend the feature instead of doing one more pre-process as post-process before generating the report.

**Comment by wswebcreation** [comment]
The mode will never have the understanding which JSON file was from which browser instance. This means that the framework should add this data during or after runtime.
I also want to keep it that way because the core is being used my multiple different frameworks and languages that use cucumber and I want to keep this module as simple as possible

**Comment by muthukumarse** [comment]
@wswebcreation well I used post-process to append metadata based my project before generating the report.

**Comment by larryg01** [comment]
@wswebcreation I am creating separate json per run and in the report whatever the last browser was it will cascade that to all the previous runs and thats despite the fact that i am generating separate jsons (filename: example-test-suite chrome Automated Test Report-1570468288493.json)

**Comment by wswebcreation** [comment]
Hi @larryg01 

Can you explain it a bit more in detail what is happening? The feature you are referring to is working as expected

**Comment by larryg01** [comment]
ok, I run the test twice on different browsers so i have
example-test-suite chrome Automated Test Report-1570521833027.json and 
example-test-suite firefox Automated Test Report-1570521851043.json
but on my report its records the last browser that was passed for both runs
<img width="1328" alt="Screenshot 2019-10-08 at 09 06 22" src="https://user-images.githubusercontent.com/22198989/66378306-14d9ac80-e9ab-11e9-8706-79dcf0272d94.png">

like its just over writing the values

**Comment by wswebcreation** [comment]
@larryg01 
Can you provide the 2 json files so I can check it here?

Can you also provide the version you are using ?

**Comment by larryg01** [comment]
I am using v1.11.6
I just change the extension from .json to .txt so that I can send them here

[example-test-suite chrome Automated Test Report-1570547715909.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/3703222/example-test-suite.chrome.Automated.Test.Report-1570547715909.txt)
[example-test-suite firefox Automated Test Report-1570547743237.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/3703223/example-test-suite.firefox.Automated.Test.Report-1570547743237.txt)

**Comment by larryg01** [comment]
@wswebcreation 
Do you have an update on this issue please

**Comment by wswebcreation** [comment]
@larryg01 

Sorry for the delay, I've checked your files but they don't have the metadata in it. I've checked them in the report itself and they look like this

![image](https://user-images.githubusercontent.com/11979740/66912458-e85d0a80-f012-11e9-85ba-cede3963b55f.png)

The metadata that can be provided like here https://github.com/wswebcreation/multiple-cucumber-html-reporter#cucumber-js-2x-and-lower

The downside if this is that it will use that metadata for ALL files, even though the are not created by the browser. Like I explained in this comment https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/82#issuecomment-473173160, the module will never have an understanding which browser generates which file because this report is a post process, when all workers are done. You need to add the metadata in a post process per worker in your own framework

**Comment by larryg01** [comment]
I am very confused because as you are seeing something different to what i am seeing, you are seeing 'not known' where as i am seeing the actual metadata value (previous image above).

Can you point me in the right direction for adding that metadata in a post process per worker, it would be greatly appreciated

**Comment by wswebcreation** [comment]
In my setup I'm not adding the metadata when the report is being build, I assume you have it set in your configuration.

About adding itinerary a postprocess, it all depends on your framework. I don't know your framework so I can't tell you how to do it.

**Comment by larryg01** [comment]
https://github.com/larryg01/klassi-js
runtime/world.js bout ln 337 (its commented out, but you will understand it) 

Thats how and where I am adding the metadata, so it means i will have to remove it from there and add it as a postproecss

**Comment by wswebcreation** [comment]
This is always overwriting the data with the latest. What you need to do is to get hold of the process in your framework that creates the JSON file, then read it and add the metadata data to it.

I can't do more for you in this case, I'm busy enough with maintaining my own modules that I don't have enough time to maintain/fix others, sorry

**Comment by larryg01** [comment]
Shouldn't it be Appending the latest data as opposed to Overwriting it so as to write the next line in the report. 
As it stands it over writes the data from all previous runs with the last run and thats only for the OS Device and Browser columns as it records the correct data for the rest ie feature, tag, status etc.

**Comment by wswebcreation** [comment]
When you call the method to create the report it will scan all files and add the metadata to all files. That's how it's build now

**Comment by wswebcreation** [comment]
@larryg01 

> if thats the case my friend how then would you get the metadata to be appended to the file so as to preserve the previous run.

As said, this needs to be done by your framework, not by this module. The purpose of this module is to collect data from a folder, enrich it if needed with predefined data and then create the report

**Comment by larryg01** [comment]
Hi am using the "saveCollectedJson: true" option and getting this error (see below) when I run the test a second time, the enriched and merged files are being created but its not generating the report 

" UnhandledPromiseRejectionWarning: TypeError: JSON.parse(...).map is not a function
    at files.map.file (/Users/lgoddard/Projects/klassi-js/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:23:30) " 

can you assist please?

NOTE: on first run the report is produced, its on the second run thats its failing with that error
