### ISSUE TITLE
All result statusses visible on index.html

### ISSUE THREAD

**Issue by SempaiPrague** [wswebcreation/multiple-cucumber-html-reporter#90]
I'm aware that this is perhaps not the best means to reach out for my question, but I hoped to reach all developers like such.

Going over the available features on the wiki-page, I saw an example report which had an interesting addition; Shown in the example of Stefano Tamagnini. But I am unable to  contact him directly with my question, hence my post here. 

The other statuses are displayed in all tables and charts, beside the default "Passed" and "Failed" statuses. (meaning Ambiguous, Not defined, Pending, Skipped are added )
as in: [https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html)
I now don't know if this is because of the custom .css styling or another feature of this tool?

Any extra info regarding this would be highly appreciated.

Kind Regards.

**Comment by wswebcreation** [comment]
@SempaiPrague 

Can you please elaborate what you are looking for? I don’t  understand what you are looking for.

**Comment by SempaiPrague** [comment]
When I now create my report, I only see 2 type of statuses. (Passed & Failed). 
But In the example of Mr Tamagnini, I can see it is possible to include also the other status types. ( Skipped, etc.)
These statuses are visible in the pie-chart and in the columns of the results.

I was trying to add this to my report, but I could not find any documentation how this should be done. And so far I was also unsuccessful with it.

**Comment by wswebcreation** [comment]
The module only shows what the JSON provides, so if you have those statuses in your Jason file and it is not showing it in the report, then there's a bug.

If you don't have them in your report then try to make a pending/skipped step.

What kind of testrunner are you using an what's the language?

**Comment by SempaiPrague** [comment]
I have in my json:
`"status": "skipped"`, but it is for a step. And when I open the scenario, I see the step marked as skipped. 
 
Im using Behave in Python. 
https://pypi.org/project/behave/

**Comment by wswebcreation** [comment]
Hi @SempaiPrague 

sorry for my late response.

> I ran an extra test and when an entire feature is skipped, it works as expected.
> So perhaps my expectations didn't met with the actual feature :).

How it works:
- the if all steps in a feature are skipped, then the feature is skipped
- the scenario chart should show the amount of skipped scenario's

So you could have skipped scenario's (you should see them in the scenario chart), but still have a feature if not all scenario's in that feature are skipped.

> Extra question:
> This seems to do the same for tags.
> Because it is correct that only tags on feature-level should be shown in the tag column? Not the ones on scenario or step level?

You have feature tags and scenario tags, in the main overview you will only see the feature tags, in a specific feature overview you can see the feature tags AND the scenario tags

Hope that makes it more clear. I'm going to close this now because based on you update this is not an issue but how the report works
